### PR TITLE
Uses instance properties instead of static properties for css classes

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
What do you guys think about keeping the naming consistent with how we name other state properties that apply css classes? Often we follow the pattern `elementClasses`, `headerClasses`, `dialogClasses` etc.

Maybe we could do something like `expandedClasses`, `collapsedClasses`, `headerExpandedClasses`, and `headerCollapsedClasses`. What do you guys think?

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, I'm all for consistency. @julien, can we make those changes on top and let us know?

Thanks!

**Comment by julien** [comment]
@jbalsas of course.

**Comment by julien** [comment]
@Robert-Frampton and @jbalsas since we're going for `expandedClasses`, `collapsedClasses` and so on, should we use the same validation? 

We expect a string but would you rather it be an array?
 
Thanks

**Comment by Robert-Frampton** [comment]
Hey @julien 

We can still expect a string, that's what we have in other components. The idea is that you can pass in something like this.

```javascript
{
    expandedClasses: 'first-class second-class'
}
```

**Comment by julien** [comment]
@Robert-Frampton thanks, just wanted to make sure I understood it correctly.

**Comment by jbalsas** [comment]
Thanks @julien! LGTM!

@Robert-Frampton, @brunobasto, double check and merge if happy with the state of the PR :)

**Pull request merged**
