### PR TITLE
Set aria-expanded attribute

### LINKED ISSUE #11: Add aria-expanded attribute to indicate the collapse state

### PR DESCRIPTION
**Pull request by jonathantneal**
Resolves #11

### CODE REVIEW

**Comment by zenorocha** [comment]
Can you ask someone to review this @jbalsas?

**Comment by jbalsas** [comment]
We are looking at adding this to our current sprint, so should be swinging around here shortly

**Comment by jonathantneal** [comment]
Wonderful.

For posterity sake, the purpose of this PR is to add **ARIA** attributes to toggle components in order to communicate its expanded or collapsed state to accessibility tools.

> `aria-expanded` indicates whether the element, or another grouping element it controls, is currently expanded or collapsed.
> — https://www.w3.org/TR/wai-aria/states_and_properties#aria-expanded

For that reason I have added `aria-expanded` to both the toggle controller _and_ the section it controls.

---

Later, I would like to expand on this PR to improve accessibility even further by adding `aria-controls` to the toggle controller in order to indicate the section it controls. This would also require adding an `id` to the section it controls. Using both `aria-controls` and `aria-expanded` is a recommended practice.

> `aria-controls` identifies the element (or elements) whose contents or presence are controlled by the current element.
> — https://www.w3.org/TR/wai-aria/states_and_properties#aria-controls

> If the element with the `aria-expanded` attribute controls the expansion of another grouping container that is not 'owned by' the element, the author SHOULD reference the container by using the `aria`-controls attribute.

---

Here are two existing, popular projects on the web following this convention:

- https://getbootstrap.com/docs/4.0/components/collapse/
- https://adobe-accessibility.github.io/Accessible-Mega-Menu/

And here is illustrative markup to summarize all of the attributes being used and what their relationship would be like:

```html
<x-control-element
  aria-controls="${ contentId }"
  aria-expanded="${ isExpanded }"
/>
<x-content-element
  id="${ contentId }"
  aria-expanded="${ isExpanded }"
  aria-hidden="${ !isExpanded }"
  aria-labelledby="${ controllerId }"
/>
```

**Comment by zenorocha** [comment]
Thanks for the detailed explanation @jonathantneal!

**Comment by Robert-Frampton** [comment]
Resent with #15.

**Pull request closed without merging**
