### PR TITLE
Normalize README.md

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by robframpton** [comment]
Hey @jbalsas,

Looks like we might still have an issue with our saucelabs account.

```
29 11 2017 19:30:14.771:ERROR [launcher.sauce]: Can not start internet explorer 10 (Windows 7)
  [init({"version":"10","platform":"Windows 7","tags":[],"name":"metal-uri tests","tunnel-identifier":"31.1","record-video":false,"record-screenshots":false,"device-orientation":null,"disable-popup-handler":true,"build":"31","public":null,"customData":{},"base":"SauceLabs","browserName":"internet explorer"})] The environment you requested was unavailable.
  Uh oh, you've run out of minutes!
Please visit https://saucelabs.com/pricing to purchase a subscription.
```

**Comment by jbalsas** [comment]
They haven't updated us to an open source account yet... and I'm not confident they will at this point, so we might need to look at other options :(

**Comment by jbalsas** [comment]
Do you want to merge the karma-launcher fix, or should we just merge the `.md` update?

**Comment by robframpton** [comment]
Let's do both, if saucelabs ends up working we'll need that dependency locked down anyways.

**Pull request merged**
